---
version: '2'
services:
  couchpotato:
    image: "linuxserver/couchpotato:latest"
    container_name: couchpotato
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/couchpotato:/config"
      - "/mnt/storage/downloads:/downloads"
      - "/mnt/storage/movies:/movies"
    ports:
      - "5050:5050"
    links:
      - deluge
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  sickrage:
    image: "linuxserver/sickrage:latest"
    container_name: sickrage
    depends_on:
      - deluge
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/sickrage:/config"
      - "/mnt/storage/downloads:/downloads"
      - "/mnt/storage/shows:/tv"
    ports:
      - "8081:8081"
    links:
      - deluge
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  sonarr:
    image: "linuxserver/sonarr:latest"
    container_name: sonarr
    depends_on:
      - deluge
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/sonarr:/config"
      - "/mnt/storage/downloads:/downloads"
      - "/mnt/storage/shows:/tv"
    ports:
      - "8989:8989"
    links:
      - deluge
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  openvpn:
    image: "linuxserver/openvpn-as:latest"
    container_name: openvpn
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/openvpn:/config"
    network_most: host
    privileged: true
    restart: unless-stopped
    environment:
      TZ: America/Chicago
      INTERFACE: eth0
      PUID: ${PUID}
      PGID: ${PGID}
  deluge:
    image: "linuxserver/deluge:latest"
    container_name: deluge
    depends_on: deluge
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/deluge:/config"
      - "/mnt/storage/downloads:/downloads"
    network_mode: host
    restart: unless-stopped
    links:
      - openvpn
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Chicago
      - PLEX_CLAIM=<claimToken>
    hostname: Media
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/appdata/plex:/config
      - /opt/transcode:/transcode
      - /mnt/storage/shows:/data/tvshows
      - /mnt/storage/movies:/data/movies
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
  plexrequests:
    image: "lsiodev/plexrequests:latest"
    container_name: requests
    depends_on:
      - couchpotato
      - plex
      - sickrage
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/appdata/plexrequests:/config"
      - "/mnt/storage:/data"
    ports:
      - "3000:3000"
    links:
      - couchpotato
      - plex
      - sickrage
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      URL_BASE: /
